### ISSUE TITLE
Unable to run .net core 3.1 application with Hangfire and Cosmos DB (Mongo Db)

### ISSUE THREAD

**Issue by nikheelneelay** [Hangfire-Mongo/Hangfire.Mongo#259]
We have recently migrated our application from VM Hosted MongoDb to Azure Cosmos MongoDB and the application stopped working. I am getting an exception:
Hangfire.Mongo.Migration.MongoMigrationException: 'Migration failed in Hangfire.Mongo.Migration.Steps.Version09.CreateSignalCollection'
MongoCommandException: Command create failed: Capped collectiosn are not supported..
I believe this is because hangfire tries to create a capped collection - hangfire.mongo.notifications which is not allowed.
My questions - Is Cosmos DB supported with Hangfire? If yes, what are the steps? Do we need to manually create any collections? What will happen when the next time the application is redepployed?

**Comment by gottscj** [comment]
@nikheelneelay ,

We dont officially support cosmos db. you can however override options to support your use case:

Thank you for your patience.

I needed to do some changes before we could progress with this.
Last things I need from you before we can merge.

Create new CosmosStorage inheriting from MongoStorage.
override "GetComponents" only return "yield return StorageOptions.Factory.CreateMongoExpirationManager(HangfireDbContext, StorageOptions);" dont return NotificationObserver. it expects a capped collection.
Create new CosmosMigrationFactory. override "GetOrderedMigrations", write new migrations specific for cosmos db and inject them into the list, remove unwanted ones.
in your "CosmosStorageOptions" you need to override the default MongoMigrationOptions. Perhaps even create a CosmosMigrationOptions class.
Create a CosmosFactory inheriting the MongoFactory. override "CreateMongoJobFetcher", with a new class with the needed changes.
In principle I would like all the CosmosDB changes to be in completely separate files from the mongo ones.

Thanks!

@lollo25, succesfully added support for this. 

If you create a PR for this, I would be happy to take it in to the official project :)

**Comment by summer9604** [comment]
Hello @gottscj, i got stuck in these steps, can you elaborate pls?
![image](https://user-images.githubusercontent.com/47285900/113182347-b3666700-924a-11eb-9b0e-ef89c21a7f5f.png)

**Comment by gottscj** [comment]
@summer9604 ,

In the newest release I added a flag to the options class. UseNotificationCollection. I believe that would support cosmosdb.
I didn't test so we might need more. Let me know

**Comment by summer9604** [comment]
Unfortunately Is was not enough:

"Could not complete migration. Never acquired lock within allowed time: 00:01:00
Either another server did not complete the migration or migration was abruptly interrupted
If migration has been interrupted you need to manually delete 'hangfire.migrationLock' and start again."

**Comment by gottscj** [comment]
Did you try what was suggested in the message?

Either the migration took more than 1 min or there is a connection issue. you can increase the wait time in the options: MigrationLockTimeOut

Is it a new environment?

**Comment by summer9604** [comment]
@gottscj sorry for late response. Yes, I did try that, no success. It is a new environment.

**Comment by gottscj** [comment]
Im planning to add CosmosDB in 0.7.21

you can check out this commit:
https://github.com/sergeyzwezdin/Hangfire.Mongo/commit/1fc0aaa329f41a6e2459a8c770baa6db6993f715
Its a bit noisy, but it "works on my machine"

**Comment by gottscj** [comment]
@pashtet04,

You need to give me more to work with. :)
what version are you using
what does your configuration look like in startup?
Did you take a look at the cosmosdb sample project?

Thanks
