### ISSUE TITLE
Hangfire dashboard scheduled jobs sort order

### ISSUE THREAD

**Issue by tylerohlsen** [Hangfire-Mongo/Hangfire.Mongo#271]
I switched from a Redis data store to this library for a Mongo data store and noticed that the sort order on the Scheduled Jobs page of the Hangfire dashboard changed.  When I had the Redis data store, the sort seems to be ascending by when the job will enqueue next.  This was nice because when I go to the dashboard, I can see what will run next on the first page.  But with this library, I now need to go to the last page to see the job that will run next.  

I think I found that [this line](https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/v0.7.19/src/Hangfire.Mongo/MongoMonitoringApi.cs#L493) determines the sort order for the dashboard.  A quick fix, for me, would be to change that sort order to _ascending_ on `_id`.  But I think the better solution would be to sort ascending by the state history scheduled at date time (though, that's a bit more involved).

**Comment by gottscj** [comment]
@tylerohlsen,

Thank you for posting.
The default behavior is based on the original behavior from the sql server implementation found [here](https://github.com/HangfireIO/Hangfire/blob/e52e0bf7fbf14a986ddefbeb6aa65cc436f47987/src/Hangfire.SqlServer/SqlServerMonitoringApi.cs#L545)

You can override the default behavior by overriding the MongomonitoringApi class and use that instead like so:

```csharp
public class MyMongoMonitoringApi : MongoMonitoringApi
{
    private readonly HangfireDbContext _dbContext;

    public MyMongoMonitoringApi(HangfireDbContext dbContext) : base(dbContext)
    {
        _dbContext = dbContext;
    }

    public override JobList<TDto> GetJobs<TDto>(int @from, int count, string stateName, Func<JobSummary, Job, Dictionary<string, string>, TDto> selector)
    {
        // only retrieve job ids
        var filter = Builders<JobDto>
            .Filter
            .Eq(j => j.StateName, stateName);

        var jobs = _dbContext
            .JobGraph
            .OfType<JobDto>()
            .Find(filter)
            .Skip(from)
            .Limit(count)
            .ToList();

        var joinedJobs = jobs
            .Select(job =>
            {
                var state = job.StateHistory.LastOrDefault(s => s.Name == stateName);
                return new JobSummary
                {
                    Id = job.Id.ToString(),
                    InvocationData = job.InvocationData,
                    Arguments = job.Arguments,
                    CreatedAt = job.CreatedAt,
                    ExpireAt = job.ExpireAt,
                    FetchedAt = null,
                    StateName = job.StateName,
                    StateReason = state?.Reason,
                    StateData = state?.Data
                };
            })
            .ToList();

        var result = new List<KeyValuePair<string, TDto>>(jobs.Count);

        foreach (var job in joinedJobs)
        {
            var stateData = job.StateData;
            var dto = selector(job, DeserializeJob(job.InvocationData, job.Arguments), stateData);
            result.Add(new KeyValuePair<string, TDto>(job.Id, dto));
        }

        return new JobList<TDto>(result);
    }
}

public class MyMongoFactory : MongoFactory
{
    public override MongoMonitoringApi CreateMongoMonitoringApi(HangfireDbContext dbContext)
    {
        return new MyMongoMonitoringApi(dbContext);
    }
}
```

You should now use you factory like so:
```csharp
var myOptions = new MongoStorageOptions
{
    Factory = new MyMongoFactory()
};
```

let me know if it works out :)
