### ISSUE TITLE
Intermittent error causes notifications to be stopped

### ISSUE THREAD

**Issue by mikenorgate** [Hangfire-Mongo/Hangfire.Mongo#276]
I noticed today during a small network issue that the `MongoNotificationObserver` seem to have stopped receiving notifications, after a quick look through the logs I saw the error message detailed here https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/7c3ae992719a0747d71380f13c97af1ef0769660/src/Hangfire.Mongo/MongoNotificationObserver.cs#L103

From what I can see of the code in this scenario you block on the cancellation token and don't restart the observer. I think it would be better to retry (maybe with an exponential backoff) to account for intermittent errors (network glitches) and so that if the collection was re-created as per the message the observer could continue without the need to restart the hosting service

**Comment by mikenorgate** [comment]
@gottscj 

Here's the full error I received 

```
Error observing 'hangfire.notifications'
interrupted at shutdown
Notifications will not be available
If you dropped the 'hangfire.notifications' collection you need to manually create it again as a capped collection
For reference, please see
   - https://docs.mongodb.com/manual/core/capped-collections/
   - https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/Migration/Steps/Version17/00_AddNotificationsCollection.cs
```

**Comment by mikenorgate** [comment]
I was just looking at the commit you made for addressing this https://github.com/sergeyzwezdin/Hangfire.Mongo/commit/5ef482af7452087593bbf091e73f673f6696f58a

Querying to check if the notification collection exists in the catch will be a problem in the scenario of a network error ,where the network has not recovered at that point. The `ListCollections` operation will throw an exception which isn't handled.

Also waiting on the cancellation token if the collection is not found does not allow for automatic recovery if the notifications collection is manually recreated, if this is desired behaviour then it would be good if the error message noted that you need to restart the server after creating the collection

**Comment by gottscj** [comment]
@mikenorgate,

Thanks for looking at the commit!
 Should I try to list collections a couple of times? how long do you suggest?
Im currently not looking to recreate the collection.
I will add that the server needs to be restarted if the collection is dropped.

**Comment by mikenorgate** [comment]
My suggestion would be to retry forever with an exponential back off, that way once the collection becomes available again (or is manually created) the notifications will resume without the need to restart

**Comment by gottscj** [comment]
@mikenorgate, 
thank you for the suggestion. I added a very simple back off mechanism delaying retry by 5s for each try, max timeout is 60s.
you can override almost all behavior in Hangfire.Mongo by overriding the MongoFactory and implement your own behavior.
If you need or would like different back off behavior, simply override the MongoNotificationObserver and return that in the MongoFactory.

**Comment by mikenorgate** [comment]
@gottscj I think that looks good. I didn't know about being able to override using MongoFactory, that might be really useful in the future
