### ISSUE TITLE
Which collections can be removed without breaking functionality?

### ISSUE THREAD

**Issue by ffMathy** [Hangfire-Mongo/Hangfire.Mongo#293]
We recently switched from Hangfire Mongo to Hangfire PostgreSQL.

However, even after running all jobs, the notifications and jobgraph collections still contain hundreds of thousands of documents.

Are these safe to delete?

In fact, which collections would I be able to delete? All of them?

**Comment by gottscj** [comment]
@ffMathy,

If you are not using hangfire.mongo you can safely delete all collections. If you had a specific database for jobs you can just delete that.

The notifications collection is a capped collection with a fixed size. Eg entities are overriden when the capsize is met. the maximum collection size is 16MB and 100K items. you can safely delete all documents. but you should not drop the collection.

Hangfire expires jobs after processing by setting the "ExpireAt" field to a value. Hangfire.Mongo checks for expired items at an interval defined by the "JobExpirationCheckInterval" setting in the storage options.

hopes this helps.

Did PostgreSQL speed up things for you?
Thanks

**Comment by ffMathy** [comment]
Thank you so much for all the help. And this library has really served its purpose for us.

Yes, switching sped everything up significantly. But it's hard to tell for sure, because we use Mongo as our primary data table for our system, which is already under quite heavy load.

However, all Hangfire-related slow-queries are no longer popping up (and they were the only ones that did), and memory usage has halved, and we no longer see CPU spikes.

What really bugs me though (and that's Hangfire's fault) is that they don't seem to have an index on the "schedule time" for scheduled messages. Not even in PostgreSQL. That's insane!

It just means that no matter what, scheduled messages will always be a bit slower than everything else.

We're currently therefore taking the scheduled message part of Hangfire into a separate custom-built system. We're keeping Hangfire for recurring jobs though (we only have like 30 of those).
