### ISSUE TITLE
Replace MongoClient for IMongoClient

### ISSUE THREAD

**Issue by simaoribeiro** [Hangfire-Mongo/Hangfire.Mongo#301]
Hi there,

In my team, we are using decorators for IMongoClient that allows us to include tracing and metrics for several of our projects that use MongoDB databases. However, the decorated code cannot be used for Hangfire.Mongo as the driver requests a MongoClient instance as a parameter for several methods instead of its interface as in the example below:

`public static MongoStorage UseMongoStorage(this IGlobalConfiguration configuration, MongoClient mongoClient, string databaseName, MongoStorageOptions storageOptions)`

I believe that the interface should be used instead of the concrete implementation to allow extensibility.

**Comment by gottscj** [comment]
changes part of v.0.7.28.
closing
