### ISSUE TITLE
Capped option not set on new collection

### ISSUE THREAD

**Issue by jwillmer** [Hangfire-Mongo/Hangfire.Mongo#304]
I'm not able to get a mongo collection with the capped option using the config example from the README. 

Below is my configuration:

```
...
        "WriteTo": [
            {
                "Name": "MongoDB",
                "Args": {
                    "databaseUrl": "mongodb://localhost:27017/site-monitor",
                    "collectionName": "monitoring.logs",
                    "restrictedToMinimumLevel": "Warning",
                    "cappedMaxSizeMb": "50",
                    "cappedMaxDocuments": "1000"
                }
            }
...
```

**Comment by gottscj** [comment]
@jwillmer,

Thanks for submitting. However. Im not sure what im looking at? Could you add more information which might be more Hangfire.Mongo specific?

Thanks!

**Comment by jwillmer** [comment]
Sorry, I will close this. I had to many tabs open and posted to the wrong repo. [This](https://github.com/serilog/serilog-sinks-mongodb/issues) is the repo I was looking for.

**Comment by jwillmer** [comment]
While I wasted your time maybe you could add the option to use a single mongo instance in the readme. Took me some time to find the poll option to make the scheduling work.
