### ISSUE TITLE
Does it support CosmosDb [question]

### ISSUE THREAD

**Issue by botrot** [Hangfire-Mongo/Hangfire.Mongo#312]
Hi there,
does the current package support cosmos db and if so do you have any example of the set-up?

**Comment by gottscj** [comment]
@botrot,

It does support cosmosdb, but I dont test it that well.
please see the CosmosDB sample:
https://github.com/Hangfire-Mongo/Hangfire.Mongo/tree/master/src/Hangfire.Mongo.Sample.CosmosDB
