### ISSUE TITLE
Return IGlobalConfiguration<MongoStorage> instead of MongoStorage in all UseMongoStorage

### ISSUE THREAD

**Issue by Ghaiath** [Hangfire-Mongo/Hangfire.Mongo#317]
Hi,

I believe that all `UseMongoStorage(this ...)` should return `IGlobalConfiguration<MongoStorage>` instead of `MongoStorage` object. In case you want to attach more extensions after initializing the MongoDb storage.

Trying to attach extensions before will case an exception _`JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.`_

_`'MongoStorage' does not contain a definition for '' and the best extension method overload '' requires a receiver of type 'IGlobalConfiguration'`_

Thanks

**Comment by gottscj** [comment]
@Ghaiath,

Thank you for the suggestion. I will try to add it for next release. 
Thanks!

**Comment by gottscj** [comment]
fixed
