### ISSUE TITLE
Mongo Atlas Compatiability

### ISSUE THREAD

**Issue by mack0196** [Hangfire-Mongo/Hangfire.Mongo#318]
I tried swapping my intranet MongoDB instance connection string with Mongo atlas and it didn't work. 

Is Mongo Altas considered compatible with Hangfire-Mongo?

**Comment by gottscj** [comment]
@mack0196,

Yes it is compatible with atlas. Can you elaborate on what your issue is. You are not giving me much to work with. 🙂
