### ISSUE TITLE
Implement transactional outbox

### ISSUE THREAD

**Issue by nike61** [Hangfire-Mongo/Hangfire.Mongo#319]
Hello!

Is it possible to update documents and enqueue job in a single MongoDB transaction? 
I'm implementing async operation API. What I want to do is to create operation object in MongoDB and enque Job in MongoDB. 
But without wrapping it in transaction there is a risk either to create operation without queueing job or to enque job without creating operation.

**Comment by gottscj** [comment]
Hi.

You can override most of the functionality in hangfire.mongo. however we do not control the list of operations hangfire is scheduling when creating enqueueing a job, so it will be a challenge to do. You can consider two phase commits instead.

Good luck!

**Comment by MohamadTahir** [comment]
Hello, 

there are no plans for adding session parameters to the functions?

**Comment by gottscj** [comment]
@MohamadTahir,

Could you elaborate on "adding session parameters to the functions"? what does that mean?

Thanks!

**Comment by MohamadTahir** [comment]
Hello @gottscj,

I am not sure how hard it is to implement this. (or if it is possible to do in this project) but here is the idea, what I mean is to add a parameter to the functions that down the line write the document to the database for example

```
public static string Schedule<T>([InstantHandle][NotNull] Expression<Func<T, Task>> methodCall, TimeSpan delay);
```

will change to something like 

```
public static string Schedule<T>([InstantHandle][NotNull] Expression<Func<T, Task>> methodCall, TimeSpan delay, IClientSessionHandle clientSession);
```

then whenever you're writing a document you pass the session, so we can do something like

```
using var session = await _mongoClient.StartSessionAsync();
session.StartTransaction();

var jobId = BackgroundJob.Schedule<MyClass>(x => x.MyFunction(), timeSpan,session);
var document = new MyCollectionDocument(){
     Id = "example",
     Topic = "scheduled a job",
     ScheduledJobId = jobId
};
_collection.InsertOne(session, document);
```
then we can 
```
await session.AbortTransactionAsync();
//or
await session.CommitTransactionAsync();
```
so we can make sure that both insertions happen together or get canceled together. I am not sure if it is possible to do this but it would be very nice if we can use transactions.

**Comment by gottscj** [comment]
@MohamadTahir,
Thank you for your explanation. The Hangfire.Core lib handles the scheduling logic. Hangfire.Mongo only handles the storage part. E.g. the BackgroundJob is in the Hangfire.Core lib.
Please also check out my answer here: https://github.com/Hangfire-Mongo/Hangfire.Mongo/issues/320#issuecomment-1250127429

Thanks!
