### ISSUE TITLE
Cannot register own DateTimeSerializer when using Hangfire.Mongo

### ISSUE THREAD

**Issue by yBother2** [Hangfire-Mongo/Hangfire.Mongo#323]
I am using (latest) MongoDb C# Driver and Hangfire extension in a solution (different projects) and
want to configure DateTime to be stored as string in none-hangfire projects.
So I register as follows:
BsonSerializer.RegisterSerializer(typeof(DateTime), new DateTimeSerializer(DateTimeKind.Utc, BsonType.String));

During start up application fails:
MongoDB.Bson.BsonSerializationException: There is already a serializer registered for type DateTime.

This is probably because extension for hangfire registers its own date time serializer.
Is it possible to limit scope for serializers, so that I can still register own Serializers?

**Comment by gottscj** [comment]
@yBother2,

Thanks for posting. We do not register custom serializers in Hangfire.Mongo, we use attributes to configure serialization.

check out: https://github.com/Hangfire-Mongo/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/Dto/ServerDto.cs

You probably need to register your serializer earlier as the mongo driver does not allow you change a serializer once it has been used.
check out the mongo driver documentation:
https://mongodb.github.io/mongo-csharp-driver/2.17/reference/bson/serialization/

**Comment by yBother2** [comment]
Indeed it works when registering before Configuring Hangfire in Startup!

**Comment by gottscj** [comment]
@yBother2,

Did it work as expected? then I will close this issue. :)

Thanks
