### ISSUE TITLE
Command aggregate failed: a collection 'XXX_Database_Name.hangfire.mongo.jobQueue.8.migrationbackup' already exists

### ISSUE THREAD

**Issue by paratoner** [Hangfire-Mongo/Hangfire.Mongo#325]
I have .net core web api project (.Net 6) (dockerized)
i have added service like this : 

```
services.AddHangfire(configuration => configuration
        .SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
        .UseSimpleAssemblyNameTypeSerializer()
        .UseRecommendedSerializerSettings()
        .UseMongoStorage(mongoClient, mongoUrlBuilder.DatabaseName, new MongoStorageOptions
        {
            MigrationOptions = new MongoMigrationOptions
            {
                MigrationStrategy = new MigrateMongoMigrationStrategy(),
                BackupStrategy = new CollectionMongoBackupStrategy()
            },
            Prefix = "hangfire.mongo",
            CheckConnection = true
        })
    );
services.AddHangfireServer(options => { options.Queues = new[] { "default", "RecurringJobQueue" }; });
```

I have Azure App Service resource that running 3 instances
it works local development machine.
I register all jobs at startup with addorupdatejob method.
i deploy my webapi app to app service and at the startup it gives the following error : 

Unhandled exception. MongoDB.Driver.MongoCommandException: Command aggregate failed: a collection 'Database_Name.hangfire.mongo.jobQueue.8.migrationbackup' already exists.

any advice appreciated
Thanks.

**Comment by gottscj** [comment]
@paratoner,

Same as #326, please try to use "UseCosmosStorage"

Hope this helps.

Thanks
