### ISSUE TITLE
Recommended index

### ISSUE THREAD

**Issue by jpineault** [Hangfire-Mongo/Hangfire.Mongo#330]
Hi. 

We've been using Hangfire.Mongo for a bit and we've noticed that Mongo Atlas has an index suggestion.
When applying the index, we've noticed considerable improvement in latency. 

The index definition would be something like this:
db.hangfire.jobGraph.createIndex({ SetType: 1, _t: 1, Score: 1 }, { name: "IX_SetType_T_Score", background: true });

Thanks!

![image](https://user-images.githubusercontent.com/8516844/203847724-8b8cd952-3bca-4f39-a1b1-73e17e66ac56.png)

**Comment by gottscj** [comment]
@jpineault,

Thank you for your post!
Which schema version are you using?

for schema 19 there should be an index for "SetType". in general your indexes for jobGraph collection should look like this:

![image](https://user-images.githubusercontent.com/12970565/204127005-4df55d29-9009-4978-9ed1-2e4ec4505471.png)
![image](https://user-images.githubusercontent.com/12970565/204127020-a6ff9243-30f6-4576-973f-2be64c7079f6.png)

**Comment by jpineault** [comment]
Hi!

We have the latest schema, and the indexes generated match your screenshots. 

Atlas is pretty spot on with their index recommendations. There might indeed be a blind spot with the current index setup.

We use Batches; maybe the recommended index is related to that?

Cheers!

**Comment by gottscj** [comment]
@jpineault,

Thanks! Yes, Batches has not been tested at all actually. Im happy it works for you.

I will add the recommended index.

**Comment by jpineault** [comment]
@gottscj 

So far so good witch batches. Jobs are queued one by one, making it a somewhat slow process, but it works. There might be opportunities to use some Mongo bulk operations. 

We also have this other index recommendation (with a lesser impact) on jobGraph: _t: 1, ExpireAt: 1

Thanks again!

**Comment by gottscj** [comment]
@jpineault,

Please let me know if everything looks OK for you, then I'll close this issue. :)

regarding bulk operations. We do not control how hangfire schedules enqueued jobs. We are using bulk operations for our write operations.

Thanks!

**Comment by jpineault** [comment]
@gottscj All is good. Indexes are created successfully. We had a bit of an issue with the migration (certain documents not updated), but it's probably due to our setup.

Thanks!
