### ISSUE TITLE
Add support to Hangfire 1.8.0

### ISSUE THREAD

**Issue by tmm360** [Hangfire-Mongo/Hangfire.Mongo#346]
From release note: https://www.hangfire.io/blog/2023/04/28/hangfire-1.8.0.html

> Storage Support Required
> The new feature requires job storage to persist a new field, which storage may not support out-of-the-box. That's why additional storage support is required. Otherwise, the NotSupportedException will be thrown. So upgrade of the job storage package is likely needed.

**Comment by gottscj** [comment]
Hi @tmm360,

It is in-progress. However there are details I need to sort out before I can release. Its very close. @odinserj is kindly assisting me.

Thanks

**Comment by gottscj** [comment]
Hi,

I just released the latest version of Hangfire.Mongo adding support for all the currently available features exposed in Hangfire.Core.

https://www.nuget.org/packages/Hangfire.Mongo/
FYI @odinserj
