### ISSUE TITLE
Errors when using Atlas Serverless

### ISSUE THREAD

**Issue by alkampfergit** [Hangfire-Mongo/Hangfire.Mongo#348]
If we connect to ATLAS in serverless mode, actually capped collection we got an error due to the fact that serverless does not supports capped collection. I do not know if I can force not to use capped collection with some storage options.

![image](https://user-images.githubusercontent.com/358545/236807491-0a471bb5-c818-425c-91da-4224cfd06db0.png)

**Comment by gottscj** [comment]
Hi,
If your setup doesnt support capped collections for notifications, you can use "Poll" strategy or "Watch".

https://github.com/Hangfire-Mongo/Hangfire.Mongo/blob/e48bff7fb3fc2ea6d2bdf00266ceaf65a26a1ba1/src/Hangfire.Mongo/MongoStorageOptions.cs#LL46C3-L46C3

Hope this helps

**Comment by rowens-an** [comment]
> Hi, If your setup doesnt support capped collections for notifications, you can use "Poll" strategy or "Watch".
> 
> https://github.com/Hangfire-Mongo/Hangfire.Mongo/blob/e48bff7fb3fc2ea6d2bdf00266ceaf65a26a1ba1/src/Hangfire.Mongo/MongoStorageOptions.cs#LL46C3-L46C3
> 
> Hope this helps

This does not fix the issue @gottscj . This line in the migrations fails in Atlas serverless regardless of the check queue job strategy https://github.com/Hangfire-Mongo/Hangfire.Mongo/blob/8963c6b4cbeb170c5a98e3b9bd92469a4c4c77f3/src/Hangfire.Mongo/Migration/Steps/Version09/00_CreateSignalCollection.cs#L27C31-L27C31 

Setting 'Capped' to true is not allowed in Atlas serverless instances.  See this limitation in Atlas https://www.mongodb.com/docs/atlas/reference/serverless-instance-limitations/#operational-limitations-and-considerations

**Comment by gottscj** [comment]
@rowens-an,
I added a check so you can opt out of creating capped collections. setting this flag to false will also disable tailing the notification collection which is used for the CheckQueuedJobsStrategy.TailNotificationsCollection

**Comment by gottscj** [comment]
@rowens-an,

did you have a chance trying out the new version?

Thanks!

**Comment by rowens-an** [comment]
Hey @gottscj I'll try version 1.9.11 real quick.

**Comment by rowens-an** [comment]
Hey @gottscj  apologies on the delay, I have a basic test project https://github.com/rowens-an/HangfireServerlessMongoTesting I used this project with a fresh Atlas Serverless database and everything is working as expected. 

Thank you for fixing this!

**Comment by gottscj** [comment]
@rowens-an,

Thank you for the feedback. 🙏

I will close the ticket.
