### ISSUE TITLE
Error scheduling job in the future with queue name

### ISSUE THREAD

**Issue by alkampfergit** [Hangfire-Mongo/Hangfire.Mongo#359]
Just create a .Net console program and use program.cs specified in this gist https://gist.github.com/alkampfergit/b46cb5e87fc9353f414fb00cd3eca981

The program is really simple, it queue a simple job in the future incrementing the delay on 1 second for each call. I'm using BackgroundJob.Schedule to schedule on different queues. What is happening is that if I'm not using queue everything works perfectly.

![image](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/358545/ad769a11-779f-4b60-95ee-548ace4098c9)

You can see that each queue gots queued one second more than the previous. Now if you schedule the job in the future using a specific queue name it got executed immediately as you can see from the following image.

![image](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/358545/447ce6c0-8e38-4dad-8762-81295c73cb86)

**Comment by gottscj** [comment]
@alkampfergit,

Thank you for your submission. Im able to reproduce the issue. Looking into it ASAP.

Thanks!
