### ISSUE TITLE
Index recommendation on jobGraph Collection

### ISSUE THREAD

**Issue by samuelcadieux** [Hangfire-Mongo/Hangfire.Mongo#368]
Hi! We've been happily using Hangfire.Mongo for the last 6 months using a cluster hosted on Mongo Atlas.

However, there are a few index recommendations on the jobGraph collection that are consistently being recommended, so I figured I would let you know:
```
{ Queue: 1, _t: 1, FetchedAt: 1 }
{ Key: 1, _t: 1 }
```

Thanks for putting this library together btw it's been a life-saver!

**Comment by gottscj** [comment]
@samuelcadieux,

Now we are at the subject, does it recommend to drop any indexes?

Thanks!

**Comment by samuelcadieux** [comment]
Hey Jonas, I've double-checked both our dev and prod cluster and the only recommendation is to drop the `ExpireAt` index from the `locks` collection.

**Comment by gottscj** [comment]
Got it. thanks!

**Comment by samuelcadieux** [comment]
Confirmed it was fixed in 1.9.14 thanks for the quick turnaround!
