### ISSUE TITLE
[Question] - InvisibilityTimeout

### ISSUE THREAD

**Issue by mwasson74** [Hangfire-Mongo/Hangfire.Mongo#370]
Could someone please explain to me the following about `InvisibilityTimeout`:
1. What is it?
2. What does it do?
3. What value should it be set to?
  a. What value should be used for "Long" running jobs?
  b. What value should be used for "Short" running jobs?
  c. Why is `null` the default if this makes "the job to stay in status 'processing' in case of an error in the application."?
  d. Why is 30minutes recommended?

I ask because I _think_ I am having an issue similar to #307. I currently have my `MongoStorageOptions` using the default (`null`) for `InvisibilityTimeout`.

Thank you,

Matt

**Comment by gottscj** [comment]
@mwasson74,

Thank you for your question.
1. "InvisibilityTimeout" is used if the processing server shuts down while executing a job. Thus the job will not run to completion. 
2. When the processing server starts up the job will still be in "processing state",  "InvisibilityTimeout" is set to catch those jobs which does finish after the given timeout value.
3. To avoid false positives, it should be set well above the time you expect your longest job will take to execute.
   c. Its disabled by default to avoid false positives.
   d. The value is taken from the original Hangfire.Sql lib without much thought. Seemed like a good choice.

if you use the Hangfire dashboard you could check out the job. Hangfire will tell you if the job was executing on a server which does not send heartbeats.

Hope this helps.

![image](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/12970565/643be549-e20f-47ff-ba80-330040be49bc)
