### ISSUE TITLE
Slow operations reported by Atlas

### ISSUE THREAD

**Issue by bourquep** [Hangfire-Mongo/Hangfire.Mongo#374]
Using `Hangfire.Mongo` v1.9.14 in production, on a Mongo Atlas M40 cluster.

The Atlas _Profiler_ reports a lot of slow operations for the `jobGraph` collection (5-6 seconds to complete):

![CleanShot 2023-11-20 at 15 15 50@2x](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/65096/34b7ff60-1f24-43b6-b07b-e13c9601840a)

Most of those slow operations are reported for this query:

```
    "find": "Contents.jobGraph",
    "filter": {
      "_t": "ListDto"
    },
    "projection": {
      "_id": 1
    },
```

Which in my case returns 227k documents.

An _explain_ on this query shows:

![CleanShot 2023-11-20 at 15 26 21@2x](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/65096/2a2aba1a-1531-41ba-b495-6b580c785702)

I believe that this long query is invoked by this code:

https://github.com/Hangfire-Mongo/Hangfire.Mongo/blob/b411aa164573c455e3b8670abb8019ee6c462d2e/src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs#L338-L344

The enclosing method, `TrimList()`, has a `key` argument which is not used as a predicate in the Mongo query, but rather as a `Where` clause in a code manipulation of the returned list.

I wonder if refactoring the code to include the `key` in the Mongo query would help?

**Comment by bourquep** [comment]
I have created the following index, and it seems to help (anecdotal evidence by explaining a few manual queries, will have to let it run for a few hours to see what Atlas Profiler has to report):

```
{
  _t: 1,
  _id: 1
}
```

Adding `_id` to the index makes the query/projection _covered_ by the index, meaning there is no need for a `FETCH` stage:

![CleanShot 2023-11-21 at 15 06 25@2x](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/65096/662d22a2-2af0-4786-ab80-49fc61850e95)

I'll get back to you in a few hours with Atlas Profiler results!

**Comment by bourquep** [comment]
So far so good!

![CleanShot 2023-11-21 at 19 35 37@2x](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/65096/fc0a878a-a13f-4c0d-8078-95c509261dcc)

**Comment by bourquep** [comment]
The index definitely helps! (last 12 hours):

![CleanShot 2023-11-22 at 09 52 48@2x](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/65096/33bae551-4785-4a15-a1ca-47f7e6d08562)

**Comment by gottscj** [comment]
@bourquep,

Thank you for the analysis!
While I Definity will be adding the index, I'm curious as to why there are so many ListDto items (227K) in the first place. My expectation was that they would be removed as they should expire.

Would it be possible for you to share your ListDto's with me? The 227K ListDto's only should be fine.
Also I will be looking into doing this in an aggregation pipeline instead. It has always been a bit of a quick and dirty solution. :)

Thanks!

**Comment by bourquep** [comment]
> I'm curious as to why there are so many ListDto items (227K) in the first place. My expectation was that they would be removed as they should expire.

We use batches a lot, maybe it is related? They do expire and they are removed.

> Would it be possible for you to share your ListDto's with me? 

Sure, here they are!

[studyo-hangfire.Contents.jobGraph.json.zip](https://github.com/Hangfire-Mongo/Hangfire.Mongo/files/13476689/studyo-hangfire.Contents.jobGraph.json.zip)

**Comment by gottscj** [comment]
@bourquep,

Looking at the ids query. 

https://github.com/Hangfire-Mongo/Hangfire.Mongo/blob/b411aa164573c455e3b8670abb8019ee6c462d2e/src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs#L338-L343

there seems to be room for further improvement in the filter as I did not take the key into account. so instead of fetching ALL ids, I can limit the count to the context of the given key like so:
```csharp
 // get all ids for given key
 var filter = new BsonDocument
{
    ["_t"] = nameof(ListDto),
    [nameof(ListDto.Item)] = key
};
 var allIds = DbContext.JobGraph
      .Find(filter)
      .Project(new BsonDocument("_id", 1))
      .ToList()
      .Select(b => b["_id"].AsObjectId)
      .ToList();
```

looking at your collection the max returned documents would be 5 for a given key.

**Comment by bourquep** [comment]
@gottscj Nice find! Then make sure to have an index on `_t, key, _id`

**Comment by gottscj** [comment]
@bourquep,

I released a patch. please let me know if it works for you.

Thanks!

**Comment by bourquep** [comment]
Looks like you forgot to create the index 😉

**Comment by bourquep** [comment]
Yes, since you're projecting `_id`, including the field in the index will make the query "covered", meaning Mongo won't have to fetch the documents in order to project the `_id`.

**Comment by gottscj** [comment]
Great!

Thank you for the help!

**Comment by bourquep** [comment]
I haven't updated to 1.9.15 yet, was waiting for the index but I'll deploy the update in the coming days and let you know.

**Comment by gottscj** [comment]
thanks! :pray:

**Comment by bourquep** [comment]
I have updated to 1.9.15 at 11:00 this morning, and it makes a huge difference!

![CleanShot 2023-12-12 at 12 54 46@2x](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/65096/35bc5500-f5b9-432c-9d0a-b20e9060f356)

**Comment by gottscj** [comment]
@bourquep,

Thank you for the feedback!
I will close this issue then. :)
