### ISSUE TITLE
Dashboard does not show exception for retries

### ISSUE THREAD

**Issue by DavidLievrouw** [Hangfire-Mongo/Hangfire.Mongo#375]
I have noticed an inconsistency between Hangfire.Mongo and other storages, like in-memory, and Redis (Hangfire.Pro):
When a job is retried, the encountered exception is not shown in the dashboard, when using Hangfire.Mongo.

When using any of the other storages I tested, the exceptions are shown on every retry.

When I use the ASP.NET Core sample, and make a job fail, I get this.

<img width="1378" alt="DefaultBehaviour" src="https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/13859270/6c66849d-45c2-4d91-83eb-f3d104e5829f">

Any of the others do this (notice the Failed-state with exception information):

<img width="1383" alt="DesiredBehaviour" src="https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/13859270/4947bdf1-36a1-431f-8b6e-382b686c1fc7">

I traced the issue down to the `MongoWriteOnlyTransaction` class. It only saves the latest StateHistory item to the database, instead of all the ones that were encountered, during handling of all the configured state filters.

I don't know if this behavior is the desired behavior. It might be for performance reasons. But in any case, to change it, I did the following:

MongoJobUpdates.cs
```cs
/// <summary>
/// Updates for a specific job
/// </summary>
public class MongoJobUpdates
{
    /// <summary>
    /// Set updates
    /// </summary>
    public BsonDocument Set { get; } = new();

    /// <summary>
    /// Push updates
    /// </summary>
    public List<BsonDocument> Pushes { get; } = new();

    /// <summary>
    /// Creates a UpdateOneModel with a filter for the given job id
    /// </summary>
    /// <param name="jobId"></param>
    /// <returns></returns>
    public UpdateOneModel<BsonDocument> CreateUpdateModel(string jobId)
    {
        var filter = new BsonDocument("_id", ObjectId.Parse(jobId));
        var update = new BsonDocument();
        if (Set.Any())
        {
            update["$set"] = Set;
        }

        if (Pushes.Any())
        {
            var pushByElement = Pushes
                .SelectMany(p => p)
                .GroupBy(elem => elem.Name)
                .Select(g => new BsonElement(g.Key, new BsonDocument("$each", new BsonArray(g.Select(e => e.Value)))));

            update["$push"] = new BsonDocument(pushByElement
                .ToDictionary(p => p.Name, p => p.Value));
        }


        var updateModel = new UpdateOneModel<BsonDocument>(filter, update);
        return updateModel;
    }
}
```

MongoWriteOnlyTransaction.cs
```cs
 public override void SetJobState(string jobId, IState state)
        {
            var stateDto = new StateDto
            {
                Name = state.Name,
                Reason = state.Reason,
                CreatedAt = DateTime.UtcNow,
                Data = state.SerializeData()
            }.Serialize();

            var updates = GetOrAddJobUpdates(jobId);
            updates.Set[nameof(JobDto.StateName)] = state.Name;
            updates.Pushes.Add(new BsonDocument(new Dictionary<string, object>
            {
                { nameof(JobDto.StateHistory), stateDto }
            }));
        }

        public override void AddJobState(string jobId, IState state)
        {
            var stateDto = new StateDto
            {
                Name = state.Name,
                Reason = state.Reason,
                CreatedAt = DateTime.UtcNow,
                Data = state.SerializeData()
            }.Serialize();

            var updates = GetOrAddJobUpdates(jobId);
            updates.Pushes.Add(new BsonDocument(new Dictionary<string, object>
            {
                { nameof(JobDto.StateHistory), stateDto }
            }));
        }
```

Now the exceptions are shown for every retry.

Should I create a PR, or is the current behavior as intended?

Thanks for your efforts.

**Comment by gottscj** [comment]
@DavidLievrouw,

I added your changes. Please let me know if it works as you expect.

Thanks for the help!

**Comment by DavidLievrouw** [comment]
Perfect! Thank you.
