### ISSUE TITLE
Storage Options for Long-Running Jobs

### ISSUE THREAD

**Issue by RagibNoor** [Hangfire-Mongo/Hangfire.Mongo#377]
I'm currently working on a long-running job with a duration ranging from 10 minutes to 3 hours. My question is about the invisibility timeout.
Should I set the invisibility timeout to 3 hours or more? My concern is that if the server shuts down during processing, won't the job be picked up by another worker until the timeout has passed?
For example, if my server shuts down after running the job for 1 hour, will the next worker pick up the job 2 hours after the server shutdown? Is my understanding correct?

Additionally, can the job be canceled immediately after the server shutdown?

With my current project configuration, I see that after 30 minutes jobs are picked by a new server: 
`"Hangfire.Mongo" Version="1.9.6"`
`"Hangfire.AspNetCore" Version="1.8.2"`

      services.AddHangfire(config =>
    config.SetDataCompatibilityLevel(CompatibilityLevel.Version_170)
        .UseSimpleAssemblyNameTypeSerializer()
        .UseMongoStorage(
            mongoClient,
            mongoUrlBuilder.DatabaseName,
            new MongoStorageOptions
            {
                MigrationOptions = new MongoMigrationOptions
                {
                    MigrationStrategy = new MigrateMongoMigrationStrategy(),
                    BackupStrategy = new CollectionMongoBackupStrategy(),
                },
                Prefix = DatabaseSchemaName,
                CheckConnection = true,
                InvisibilityTimeout = TimeSpan.FromMinutes(30),
            }).UseConsole());       
![image](https://github.com/Hangfire-Mongo/Hangfire.Mongo/assets/21287489/1ab7ab91-2af2-4869-b6fe-4a81818f9e8e)

**Comment by gottscj** [comment]
@RagibNoor,

The invisibility timeout is disabled by default. eg. null. If you want to use it, and you can't split up your background work into smaller workloads, you should set the value to a value you are sure exceeds your longest job.

I hope this helps. :)

**Comment by gottscj** [comment]
@RagibNoor,

if the server crashes mid job, a new instance of hangfire server would pick it up after the invisibility timeout has been exceeded. So if you set 1h the job would "hang" for 1h before being retried.

Hope this helps.

**Comment by gottscj** [comment]
closing
