### ISSUE TITLE
Continue after a batch job does not work

### ISSUE THREAD

**Issue by Hugh-walsh** [Hangfire-Mongo/Hangfire.Mongo#60]
Queueing up 2 jobs (see below) executes the first job OK but the second one does not execute at all.

var jobTag = BatchJob.StartNew(x =>
{
    foreach (var lcOverrideWithTemplate in overrides)
    {
        x.Enqueue<IStaticsWorkerTasks>(t => t.CalculateLoadcase(designId, dutyCycleId, lcOverrideWithTemplate.templateLoadCaseId, lcOverrideWithTemplate.loadCaseOverride, progressID));
    }
});
jobTag = BatchJob.ContinueWith(jobTag, inbatch =>
{
    foreach (var bearingId in bearingIds)
    {
        inbatch.Enqueue<IStaticsWorkerTasks>(t => t.CalculateOneBearingsLifeTest(designId, histogramTestId.GetValueOrDefault(), bearingId, progressID));
    }
});

**Comment by gottscj** [comment]
Hi @Hugh-walsh,

Thank you for submitting this. Unfortunately we don't have access to Hangfire.Pro features, this is uncharted territory. 

We will contact @odinserj to try to get support on this.

**Comment by odinserj** [comment]
Hi @gottscj, there may be problems even with regular background jobs as well. I've noticed that the `MongoWriteOnlyTransaction.Commit` method isn't atomic, and there may be problems with consistency. Nobody should see/modify the data referenced by a transaction, when it's running, and it should be either fully performed, or fully rolled back. I'm not sure how to achieve this with MongoDB, and don't know whether this can be achieved there at all, but perhaps the isolation operator at least can help with isolation.

This can lead to consistency issues:
1. Thread A creates a background job for a batch with a single job, and enqueues it.
2. Thread B fetches the background job and executes it.
3. Thread A creates batch data structures, but too late – Thread B already processed the only job.

**Comment by gottscj** [comment]
Hi @odinserj,

Thank you for the feedback. We will look into honor the need for atomic commits. Its definitely possible to fix. either with distributed lock or two phase commits.

**Comment by gottscj** [comment]
closing
