### ISSUE TITLE
Each enqueued job is created twice via Hangfire.Pro BatchJob feature

### ISSUE THREAD

**Issue by TimVoo** [Hangfire-Mongo/Hangfire.Mongo#67]
Hi, 

When creating a batchrequest via Hangfire.Pro, for each job i create for that batchreqeust , two are getting created.
So in the Hangfire.Dashboard, when i create 100 jobs, it's shows 200 jobs.  My batch request never finishes, because it is only tries executing 100 jobs.

`BatchJob.StartNew(batch =>
            {
                for (int i = 0; i < 2500; i++)
                {
                    batch.Enqueue(() => DoWork());
                  
                }
            });`

**Comment by gottscj** [comment]
with 0.5.13 we finally have our writeonlytransaction atomic. I have been granted a dev license from @odinserj, so I can begin to test this feature.

**Comment by gottscj** [comment]
with 0.5.13 we finally have our writeonlytransaction atomic. I have been granted a dev license from @odinserj, so I can begin to test this feature.

**Comment by gottscj** [comment]
closing
